### ISSUE TITLE
Problem with updating package

### ISSUE THREAD

**Issue by HamzaAjmal** [agoldst/dfrtopics#7]
Dear Andrew,

I am trying to update the package but its giving the following error.

devtools::install_github("agoldst/dfrtopics")
Downloading github repo agoldst/dfrtopics@master
Installing dfrtopics
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/08/74jhwt0s54gb6pfr3byyy1ww0000gn/T/RtmpyE0efn/devtoolsa4525bc153d3/agoldst-dfrtopics-2235503'  \
  --library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library'  \
  --install-tests 
- installing _source_ package ‘dfrtopics’ ...
  *\* libs
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  ERROR: compilation failed for package ‘dfrtopics’
- removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/dfrtopics’
- restoring previous ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/dfrtopics’
  Error: Command failed (1)

What is the way of getting around it.

Regards,

Hamza

**Comment by agoldst** [comment]
I very much doubt this is a package issue. There are many google hits for [xcrun: error: invalid active developer path](https://www.google.com/search?q=xcrun%3A+error%3A+invalid+active+developer+path&ie=utf-8&oe=utf-8). Try installing or reinstalling XCode.
